In [5]:
import torch
x=torch.tensor([[1.,-1.],[1.,1.]],requires_grad=True)
out=x.pow(2).sum()
out.backward()
print(x)
print(out)
print(x.grad)

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)
tensor(4., grad_fn=<SumBackward0>)
tensor([[ 2., -2.],
        [ 2.,  2.]])


In [20]:
x=torch.randn(3,requires_grad=True)
y=x+2
z=y*y*+2
z=z.mean()
z.backward()
print(x.grad)


tensor([4.8938, 3.7899, 4.3716])
None


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  import sys


In [25]:
x=torch.randn(3,requires_grad=True)
y=x+2
z=y*y*+2
v=torch.tensor([1.,1.00,1.1],dtype=torch.float32) # need vector to compute gradient
z.backward(v)
print(x.grad)


tensor([ 5.9261, 11.6729,  5.9292])


In [22]:
x=torch.randn(3)
y=x+2
z=y*y*+2
z=z.mean()
z.backward() # gives error due to deafult requires_grad funtion is false
print(x.grad)

RuntimeError: ignored

In [23]:
x=torch.randn(3, requires_grad=False)
y=x+2
z=y*y*+2
z=z.mean()
z.backward() # gives error due to deafult requires_grad funtion is false
print(x.grad)

RuntimeError: ignored

In [27]:
x=torch.randn(5,requires_grad=True)
print(x)
y=x+2
print(y)

tensor([-0.3096,  0.5154, -0.1457, -0.3522, -0.0773], requires_grad=True)
tensor([1.6904, 2.5154, 1.8543, 1.6478, 1.9227], grad_fn=<AddBackward0>)


In [6]:
# create tensors
x=torch.tensor(1., requires_grad=True)
w=torch.tensor(2.,requires_grad=True)
b=torch.tensor(3., requires_grad=True)
y=w*x+b
y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [17]:
import torch.nn as nn
# create torch tensor
x=torch.randn(10,3)
y=torch.randn(10,2)
# build linear model
linearm=nn.Linear(3,2)
print("w:",linearm.weight)
print("bias:",linearm.bias)
# build loss function and optimizers
loss_fun=nn.MSELoss()
optimizer=torch.optim.SGD(linearm.parameters(),lr=0.01)
# forward 
pred=linearm(x)
# compute loss
loss=loss_fun(pred,y)
# print the loss
print("loss",loss.item())
# backward
loss.backward()
# print the gradients
print("gradient w:",linearm.weight.grad)
print("gradient b:",linearm.bias.grad)
# update the gradient
optimizer.step()
########################## first iteration ##################
# forward 
pred=linearm(x)
# compute loss
loss=loss_fun(pred,y)
# print the loss
print("loss after one iteration",loss.item())
# backward
loss.backward()
optimizer.zero_grad()
# print the gradients
print("gradient w:",linearm.weight.grad)
print("gradient b:",linearm.bias.grad)
# update the gradient
optimizer.step()

################################### second ieration ################
# forward 
pred=linearm(x)
# compute loss
loss=loss_fun(pred,y)
# print the loss
print("loss after second iteration",loss.item())
optimizer.zero_grad()
# print the gradients
print("gradient w:",linearm.weight.grad)
print("gradient b:",linearm.bias.grad)
# update the gradient
optimizer.step()

w: Parameter containing:
tensor([[-0.2236,  0.3833, -0.3175],
        [-0.2632,  0.0868, -0.0591]], requires_grad=True)
bias: Parameter containing:
tensor([ 0.5487, -0.0647], requires_grad=True)
loss 0.750349760055542
gradient w: tensor([[-0.3990,  0.6706,  0.1255],
        [-0.6236,  0.1537,  0.1243]])
gradient b: tensor([ 0.5347, -0.2214])
loss after one iteration 0.736577570438385
gradient w: tensor([[0., 0., 0.],
        [0., 0., 0.]])
gradient b: tensor([0., 0.])
loss after one iteration 0.736577570438385
gradient w: tensor([[0., 0., 0.],
        [0., 0., 0.]])
gradient b: tensor([0., 0.])


In [47]:
# define dataset and model here
import torch.nn as nn
# create torch tensor
x=torch.randn(10,3)
y=torch.randn(10,2)
# build linear model
linearm=nn.Linear(3,2)
# build loss function and optimizers
loss_fun=nn.MSELoss()
optimizer=torch.optim.SGD(linearm.parameters(),lr=0.01)

# compute loss and gradient for 10 epochs
for epoch in range(10):
  # forward 
  pred=linearm(x)
  optimizer.zero_grad() # zero the gradient after each epoch
  # compute loss
  loss=loss_fun(pred,y)
  # print the loss
  print(f"loss for {epoch}",loss.item())
  # backward
  loss.backward()
  #optimizer.zero_grad()
  # print the gradients
  print(f"gradient w:{epoch}:",linearm.weight.grad)
  print(f"gradient b:{epoch}",linearm.bias.grad)
  # update the gradient
  optimizer.step()

loss for 0 2.306525468826294
gradient w:0: tensor([[ 0.1109,  0.0764, -0.1833],
        [ 0.7244, -0.7563, -1.0000]])
gradient b:0 tensor([-0.9023,  0.0085])
loss for 1 2.2770919799804688
gradient w:1: tensor([[ 0.1109,  0.0730, -0.1821],
        [ 0.7183, -0.7448, -0.9826]])
gradient b:1 tensor([-0.8935,  0.0035])
loss for 2 2.248426914215088
gradient w:2: tensor([[ 0.1109,  0.0695, -0.1809],
        [ 0.7123, -0.7335, -0.9655]])
gradient b:2 tensor([-0.8848, -0.0013])
loss for 3 2.2205071449279785
gradient w:3: tensor([[ 0.1109,  0.0662, -0.1797],
        [ 0.7063, -0.7223, -0.9487]])
gradient b:3 tensor([-0.8762, -0.0060])
loss for 4 2.1933109760284424
gradient w:4: tensor([[ 0.1109,  0.0629, -0.1784],
        [ 0.7004, -0.7113, -0.9322]])
gradient b:4 tensor([-0.8678, -0.0106])
loss for 5 2.166815996170044
gradient w:5: tensor([[ 0.1109,  0.0597, -0.1772],
        [ 0.6946, -0.7005, -0.9159]])
gradient b:5 tensor([-0.8593, -0.0151])
loss for 6 2.1410017013549805
gradient w:6: tenso

In [48]:
# define dataset and model here
import torch.nn as nn
# create torch tensor
x=torch.randn(10,3)
y=torch.randn(10,2)
# build linear model
linearm=nn.Linear(3,2)
# build loss function and optimizers
loss_fun=nn.MSELoss()
optimizer=torch.optim.SGD(linearm.parameters(),lr=0.01)

# compute loss and gradient for 10 epochs
for epoch in range(10):
  # forward path 
  pred=linearm(x)
  #optimizer.zero_grad() if I did not put gradient zeros here
  # compute loss
  loss=loss_fun(pred,y)
  # print the loss
  print(f"loss for {epoch}",loss.item())
  # backward path and compute the gradient
  loss.backward()
  #optimizer.zero_grad()
  # print the gradients
  print(f"gradient w:{epoch}:",linearm.weight.grad) # gradient adding after every epochs
  print(f"gradient b:{epoch}",linearm.bias.grad)
  # update the gradient, weights and biases 
  optimizer.step()

loss for 0 0.72789466381073
gradient w:0: tensor([[-0.1942, -0.1736,  0.0471],
        [ 0.6225,  0.0927, -0.2185]])
gradient b:0 tensor([ 0.0836, -0.2209])
loss for 1 0.7222256660461426
gradient w:1: tensor([[-0.3856, -0.3464,  0.0946],
        [ 1.2376,  0.1849, -0.4370]])
gradient b:1 tensor([ 0.1674, -0.4405])
loss for 2 0.7111088037490845
gradient w:2: tensor([[-0.5717, -0.5175,  0.1428],
        [ 1.8380,  0.2759, -0.6556]])
gradient b:2 tensor([ 0.2514, -0.6574])
loss for 3 0.6949760913848877
gradient w:3: tensor([[-0.7500, -0.6861,  0.1919],
        [ 2.4167,  0.3653, -0.8744]])
gradient b:3 tensor([ 0.3358, -0.8702])
loss for 4 0.6744505167007446
gradient w:4: tensor([[-0.9179, -0.8515,  0.2422],
        [ 2.9668,  0.4525, -1.0931]])
gradient b:4 tensor([ 0.4206, -1.0775])
loss for 5 0.6503175497055054
gradient w:5: tensor([[-1.0731, -1.0130,  0.2940],
        [ 3.4819,  0.5371, -1.3117]])
gradient b:5 tensor([ 0.5058, -1.2780])
loss for 6 0.623489260673523
gradient w:6: tenso

In [54]:
# check the gradient accumulation
import torch
weight=torch.ones(4,requires_grad=True)
for epoch in range(3):
  weightmodel=(weight*3).sum()
  weightmodel.backward()
  print(weight.grad) # accumluate the gradients at every epoch
  #weight.grad.zero_()


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [55]:
# check the gradient accumulation
import torch
weight=torch.ones(4,requires_grad=True)
for epoch in range(3):
  weightmodel=(weight*3).sum()
  weightmodel.backward()
  print(weight.grad)
  weight.grad.zero_() # use grad_zero to get same gradient after every epoch

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [59]:
# check the gradient accumulation
import torch
weight=torch.ones(4,requires_grad=True)
for epoch in range(3):
  weightmodel=(weight*3).sum()
  print(weight.grad)
  weightmodel.backward()
  print(weight.grad)
  #print(weight.grad.zero_()) # use grad_zero to get same gradient after every epoch

None
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [60]:
# very basic and simple exmaple using graident computation based on simple model
import torch
X=torch.tensor(1.)
Y=torch.tensor(2.)
w=torch.tensor(1., requires_grad=True)
# forward pass
y1=w*x
# compute the loss
loss=(y1-y)**2
#backward pass
loss.backward()
print(loss)
print(loss.item())
# check the gradient
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
1.0
tensor(-2.)
