In [ ]:
# define data list of list
data = [[1,2,7],[3, 4,6],[3,4,5]]
# convert data into tensor
x_data = torch.tensor(data)
# check shape,dimension
print(f"tensor shape:{x_data.shape}")
print(f"tensor diemsnoin type1:{x_data.ndim}")
print(f"tensor diemnsion type2: {x_data.ndimension()}")
print(f"Device tensor is stored on: {x_data.device}")

tensor shape:torch.Size([3, 3])
tensor diemsnoin type1:2
tensor diemnsion type2: 2
Device tensor is stored on: cpu


In [ ]:
import numpy as np
data_x=np.ones((100,100))
print(data_x.dtype) # float64 nd array
# numpy array to tensor
data_xtorch=torch.tensor(data_x) # convert into tensor
print(data_xtorch.shape)
print(data_xtorch.dtype) # type tensor would be float64
print(data_xtorch.type(torch.float).dtype) # convert tensor float64 to float32
print(data_xtorch.ndim) # check diemsion

float64
torch.Size([100, 100])
torch.float64
torch.float32
2


In [ ]:
import torch
x = torch.rand(3,4)
print(x.dtype)  # bydefalut tensor type is float32
if torch.cuda.is_available():
  x=x.to('cuda')  # if cuda avalible then pass tensor to cuda
print(x)

torch.float32
tensor([[0.0412, 0.2367, 0.0714, 0.1528],
        [0.3248, 0.0675, 0.8382, 0.2060],
        [0.0081, 0.9743, 0.7820, 0.0065]], device='cuda:0')


**torch.dtype**

**CLASStorch.dtype **

A torch.dtype is an object that represents the data type of a torch.Tensor. PyTorch has twelve different data types:

**Data type**

dtype 32-bit floating point,torch.float32 or torch.float, torch.*.FloatTensor, 64-bit floating point, torch.float64 or torch.double 

torch.*.DoubleTensor, 64-bit complex, torch.complex64 or torch.cfloat, 128-bit complex, torch.complex128 or torch.cdouble 16-bit floating point 1, torch.float16 or torch.half

torch.*.HalfTensor, 16-bit floating point 2, torch.bfloat16 ,torch.*.BFloat16Tensor,8-bit integer (unsigned), torch.uint8

torch.*.ByteTensor, 8-bit integer (signed), torch.int8, torch.*.CharTensor, 16-bit integer (signed), torch.int16 or torch.short
torch.*.ShortTensor, 32-bit integer (signed), torch.int32 or torch.int, torch.*.IntTensor, 64-bit integer (signed), torch.int64 or torch.long, torch.*.LongTensor

Boolean, torch.bool, torch.*.BoolTensor 
https://pytorch.org/docs/stable/tensor_attributes.html)

In [ ]:
float_t=torch.randn(5,dtype=torch.float)
print(float_t)
print(float_t.dtype)

tensor([-0.9173, -1.3762, -0.1147, -2.0637,  1.5621])
torch.float32


In [ ]:
double_t=torch.randn(5,dtype=torch.double)
print(double_t)
print(double_t.dtype)

tensor([ 0.2981, -0.5040,  0.4718,  1.7251,  0.4887], dtype=torch.float64)
torch.float64


In [ ]:
complex_double_t=torch.ones(5,dtype=torch.complex64)
print(complex_double_t)
print(complex_double_t.dtype)

tensor([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])
torch.complex64


In [ ]:
complex_double_t128=torch.ones(5,dtype=torch.complex128)
print(complex_double_t128)
print(complex_double_t128.dtype)

tensor([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j], dtype=torch.complex128)
torch.complex128


In [ ]:
int_t=torch.ones(5,dtype=torch.int)
print(int_t)
print(int_t.dtype)

tensor([1, 1, 1, 1, 1], dtype=torch.int32)
torch.int32


In [ ]:
long_t=torch.ones(5,dtype=torch.long)
print(long_t)
print(long_t.dtype)

tensor([1, 1, 1, 1, 1])
torch.int64


In [ ]:
uint_t=torch.ones(5,dtype=torch.uint8)
print(uint_t)
print(uint_t.dtype)

tensor([1, 1, 1, 1, 1], dtype=torch.uint8)
torch.uint8


In [ ]:
bool_t=torch.ones(5,dtype=torch.bool)
print(bool_t)
print(bool_t.dtype)

tensor([True, True, True, True, True])
torch.bool


In [ ]:
double_t=torch.ones(5,dtype=torch.double)
print(double_t)
print(double_t.dtype)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
torch.float64


In [ ]:
# zero-dim tensors
long_zerodim = torch.tensor(1, dtype=torch.long)
int_zerodim = torch.tensor(1, dtype=torch.int)
print(long_zerodim.dtype)
print(int_zerodim.dtype)

torch.int64
torch.int32


In [ ]:
torch.add(5,5).dtype

torch.int64

In [ ]:
print(int_t.dtype)
print((int_t+5).dtype)

torch.int32
torch.int32


In [ ]:
print(int_t.dtype) # int32
print(long_zerodim.dtype) # int64
print((int_t+long_zerodim).dtype) # int32

torch.int32
torch.int64
torch.int32


In [ ]:
print(long_t.dtype) # int64
print(int_t.dtype)  # int32
print((long_t + int_t).dtype) # int64

torch.int64
torch.int32
torch.int64


In [ ]:
print(bool_t.dtype) # bool
print(long_t.dtype) # int64
print((bool_t + long_t).dtype) # int64

torch.bool
torch.int64
torch.int64


In [ ]:
print(bool_t.dtype) # bool
print(uint_t.dtype) # uint8
print((bool_t + uint_t).dtype) #uint8

torch.bool
torch.uint8
torch.uint8


In [ ]:
print(float_t.dtype) # float32
print(double_t.dtype) # float64
print((float_t + double_t).dtype) # float64

torch.float32
torch.float64
torch.float64


In [ ]:
print(bool_t.dtype) # bool
print(int_t.dtype)  # int32
print((bool_t + int_t).dtype) # int32

torch.bool
torch.int32
torch.int32


In [ ]:
print(long_t.dtype) #int64
print(float_t.dtype) #float32
print(torch.add(long_t, float_t).dtype) #float32

torch.int64
torch.float32
torch.float32


**Bridge with NumPy**

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [ ]:
# tensor to numpy array
x=torch.ones(5).numpy() # torch tensor to numpy 
print(x)
print(x.dtype)

In [ ]:
#NumPy array to Tensor
import numpy as np
an=np.ones(5)
print(an)
print(an.dtype)
at=torch.from_numpy(a) # from numpy to torch tensor
at=at.type(torch.float) # set the dtype of tensor as you wish
print(at)
print(at.dtype)

**torch.device**

**CLASStorch.device **

A torch.device is an object representing the device on which a torch.Tensor is or will be allocated.

The torch.device contains a device type ('cpu' or 'cuda') and optional device ordinal for the device type. 

If the device ordinal is not present, this object will always represent the current device for the device type, even after torch.cuda.set_device() is called; e.g., a torch.Tensor constructed with device 'cuda' is equivalent to 'cuda:X' where X is the result of torch.cuda.current_device().

A torch.Tensor’s device can be accessed via the Tensor.device property.

A torch.device can be constructed via a string or via a string and device ordinal


In [ ]:
# intilaize the device for torch tensor
torch.device('cuda:0')

device(type='cuda', index=0)

In [ ]:
torch.device('cpu')

device(type='cpu')

In [ ]:
torch.device('cuda')
torch.device('cuda', 0)
torch.device('cpu', 0)

device(type='cpu', index=0)

In [ ]:
>>> # Example of a function that takes in a torch.device
>>> cuda1 = torch.device('cuda:1')
>>> torch.randn((2,3), device=cuda1)

In [ ]:
import torch
cuda1=torch.device('cuda:0')
x=torch.randn((2,3),device=cuda1)
print(x)

tensor([[-1.3950,  1.5523, -0.3570],
        [-1.2935,  0.5708, -0.0853]], device='cuda:0')


In [ ]:
print(torch.randn((2,3),device=torch.device('cuda:0')))
print(torch.randn((2,3),device='cuda:0'))
print(torch.randn((2,3),device=0))

tensor([[ 0.6482,  0.4291, -1.0243],
        [-0.5464, -0.0588,  1.0120]], device='cuda:0')
tensor([[ 1.4443,  0.8270, -0.8968],
        [ 0.8978,  0.0145, -1.5503]], device='cuda:0')
tensor([[-2.0234, -0.2277, -0.4933],
        [ 0.0834,  0.0623,  1.0968]], device='cuda:0')


**Baisc operations in pytorch**

**zeros**
Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument size.

**ones**

Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument size.

**arange**

Returns a 1-D tensor of size with values from the interval **⌈(end-start/step⌉** 
**[start, end)** taken with common difference **step** beginning from start.

**range**

Returns a 1-D tensor of size **⌊ end−start/step⌋+1** 
with **start** to **end** with **step**.

(https://pytorch.org/docs/stable/torch.html#)

In [ ]:
import torch
num1d=torch.ones(5)
#print(num1d)
print(num1d.shape)
print(num1d.ndimension())
numb2d=torch.ones(5,5)
#print(numb2d)
print(numb2d.shape)
print(numb2d.ndimension())
numb3d=torch.ones(5,5,5)
#print(numb3d)
print(numb3d.shape)
print(numb3d.ndimension())


torch.Size([5])
1
torch.Size([5, 5])
2
torch.Size([5, 5, 5])
3


In [ ]:
import torch
num1d=torch.zeros(5)
print(num1d)
print(torch.get_default_dtype()) # get deafult type of tensor
print(num1d.shape)
print(num1d.ndimension())
numb2d=torch.zeros(5,5)
#print(numb2d)
print(numb2d.shape)
print(numb2d.ndimension())
numb3d=torch.zeros(5,5,5)
#print(numb3d)
print(numb3d.shape)
print(numb3d.ndimension())


tensor([0., 0., 0., 0., 0.])
torch.float64
torch.Size([5])
1
torch.Size([5, 5])
2
torch.Size([5, 5, 5])
3


In [ ]:
arangetensor=torch.arange(0,32) # 32 total numbers with start and zeros and end less than 1
print(arangetensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])


In [ ]:
rangetnesnor=torch.range(0,32) # 33 total numbers
rangetnesnor

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32.])

**Indexing, Slicing, Joining, Mutating Ops**


**cat**

Concatenates the given sequence of **seq** tensors in the given dimension.

**movedim**

Moves the dimension(s) of input at the position(s) in source to the position(s) in destination.

**reshape**

Returns a tensor with the same data and number of elements as input, but with the specified shape.

**squeeze**

Returns a tensor with all the dimensions of input of size 1 removed.

**unsqueeze**

Returns a new tensor with a dimension of size one inserted at the specified position.


**t**

Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.

**transpose**

Returns a tensor that is a transposed version of input.


**stack**

Concatenates a sequence of tensors along a new dimension.

**vstack**

Stack tensors in sequence vertically (row wise).

**hstack**

Stack tensors in sequence horizontally (column wise).


In [ ]:
x=torch.rand(1,5)
print(x)
print(x.shape)
t1 = torch.cat([x, x, x], dim=1) # concatenation of tensor along columns
print(t1)
print(t1.shape)
t2 = torch.cat([x, x, x], dim=0) # concatenation of tensor along rows
print(t2)
print(t2.shape)

tensor([[0.9737, 0.1033, 0.6398, 0.5075, 0.7857]])
torch.Size([1, 5])
tensor([[0.9737, 0.1033, 0.6398, 0.5075, 0.7857, 0.9737, 0.1033, 0.6398, 0.5075,
         0.7857, 0.9737, 0.1033, 0.6398, 0.5075, 0.7857]])
torch.Size([1, 15])
tensor([[0.9737, 0.1033, 0.6398, 0.5075, 0.7857],
        [0.9737, 0.1033, 0.6398, 0.5075, 0.7857],
        [0.9737, 0.1033, 0.6398, 0.5075, 0.7857]])
torch.Size([3, 5])


In [ ]:
# movedim dimension along different dimensions specified
x = torch.randn(3,2,1)
print(x.shape)
xnew=torch.movedim(x,1,0)
print(xnew.shape)
xnew1=torch.movedim(x,1,2)
print(xnew1.shape)

xnew2=torch.movedim(x, (1, 2), (0, 1))
print(xnew2.shape)

torch.Size([3, 2, 1])
torch.Size([2, 3, 1])
torch.Size([3, 1, 2])
torch.Size([2, 1, 3])


In [ ]:
x=torch.rand(1,12)
print(x)
print(x.shape)
xreshape=torch.reshape(x,(3,4))
print(xreshape)
print(xreshape.shape)

xreshape1=torch.reshape(x,(6,2))
print(xreshape1)
print(xreshape1.shape)

xreshape2=torch.reshape(x,(-1,))
print(xreshape2)
print(xreshape2.shape)

tensor([[0.5152, 0.0540, 0.6101, 0.9915, 0.7878, 0.8535, 0.7366, 0.4386, 0.0592,
         0.4376, 0.5119, 0.3922]])
torch.Size([1, 12])
tensor([[0.5152, 0.0540, 0.6101, 0.9915],
        [0.7878, 0.8535, 0.7366, 0.4386],
        [0.0592, 0.4376, 0.5119, 0.3922]])
torch.Size([3, 4])
tensor([[0.5152, 0.0540],
        [0.6101, 0.9915],
        [0.7878, 0.8535],
        [0.7366, 0.4386],
        [0.0592, 0.4376],
        [0.5119, 0.3922]])
torch.Size([6, 2])
tensor([0.5152, 0.0540, 0.6101, 0.9915, 0.7878, 0.8535, 0.7366, 0.4386, 0.0592,
        0.4376, 0.5119, 0.3922])
torch.Size([12])


In [ ]:
y=torch.tensor([[1,3,4],[4,5,6],[6,8,9],[17,18,23]])
print(y.shape)
y1=torch.reshape(y,(-1,))
print(y1.shape)

torch.Size([4, 3])
torch.Size([12])


In [ ]:
# squeeze in pytorch to reduce diemsnion
import torch
x=torch.randn(1,10,20)
print(x.shape)
xseq=torch.squeeze(x)
print(xseq.shape)

torch.Size([1, 10, 20])
torch.Size([10, 20])


In [ ]:
# unsqueeze in pytorch to increase diemsnion
import torch
x=torch.randn(1,10,20)
print(x.shape)
xuseq=torch.unsqueeze(x,dim=1)
print(xuseq.shape)

torch.Size([1, 10, 20])
torch.Size([1, 1, 10, 20])


In [ ]:
# stack two tensors
t1=torch.rand(5)
t2=torch.ones(5)
ts=torch.stack((t1,t2))
print(ts)
print(ts.shape)

tensor([[0.8965, 0.0918, 0.4821, 0.8499, 0.4759],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])
torch.Size([2, 5])


In [ ]:
# stack two tensors in vertically
t1=torch.rand(10)
t2=torch.ones(10)
tsv=torch.vstack((t1,t2))
print(tsv)
print(tsv.shape)

tensor([[0.5035, 0.7534, 0.7513, 0.0312, 0.0818, 0.1972, 0.9045, 0.0037, 0.7011,
         0.5736],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])
torch.Size([2, 10])


In [ ]:
# stack two  in horizontally
t1=torch.rand(10)
t2=torch.ones(10)
tsh=torch.hstack((t1,t2))
print(tsh)
print(tsh.shape)

tensor([0.0628, 0.7914, 0.1757, 0.0529, 0.8150, 0.6554, 0.0191, 0.8422, 0.0205,
        0.1858, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000])
torch.Size([20])


In [ ]:
# transpose diemsnion using different dimension
z=torch.rand(3,5,10)
print(z.shape)
zt=torch.transpose(z,1,2)
print(zt.shape)

torch.Size([3, 5, 10])
torch.Size([3, 10, 5])


In [ ]:
# transpose diemsnion using different dimension
z=torch.rand(5,10)
print(z.shape)
zt=torch.t(z)
print(zt.shape)

torch.Size([5, 10])
torch.Size([10, 5])


**Reduction Ops**

**argmax**

Returns the indices of the maximum value of all elements in the input tensor.

**argmin**

Returns the indices of the minimum value of all elements in the input tensor.

**amax**

Returns the maximum value of each slice of the input tensor in the given dimension(s) dim.

**amin**

Returns the minimum value of each slice of the input tensor in the given dimension(s) dim.

**max**

Returns the maximum value of all elements in the input tensor.

**min**

Returns the minimum value of all elements in the input tensor.

**mean**

Returns the mean value of all elements in the input tensor.

**median**

Returns the median value of all elements in the input tensor.

**mode**

Returns a namedtuple (values, indices) where values is the mode value of each row of the input tensor in the given dimension dim, i.e.

**norm**

Returns the matrix norm or vector norm of a given tensor.

**prod**

Returns the product of all elements in the input tensor.

**std**

Returns the standard-deviation of all elements in the input tensor.

**std_mean**

Returns the standard-deviation and mean of all elements in the input tensor.

**sum**

Returns the sum of all elements in the input tensor.

**unique**

Returns the unique elements of the input tensor.

**var**

Returns the variance of all elements in the input tensor.

**var_mean**

Returns the variance and mean of all elements in the input tensor.

**count_nonzero**

Counts the number of non-zero values in the tensor input along the given dim.

In [ ]:
#argmax 
#Returns the indices of the maximum value of all elements in the input tensor.
import torch
t=torch.randn(3,4)
print(t)
targ=torch.argmax(t) # get the index of maximum value
print(targ)

tensor([[-0.3729,  0.1159, -0.1202,  1.6675],
        [-1.2227,  0.0171, -0.0381, -0.2619],
        [ 1.7625,  0.1828, -1.1025,  0.6088]])
tensor(8)


In [ ]:
#argmin 
#Returns the indices of the maximum value of all elements in the input tensor.
import torch
t=torch.randn(3,4)
print(t)
targm=torch.argmin(t) # get the index of minimum value
print(targm)

tensor([[-1.1419,  1.2887,  0.3504, -1.8382],
        [ 0.3498,  0.6506,  0.3072, -1.2504],
        [ 1.1490,  1.8750,  0.8094,  0.1909]])
tensor(3)


In [ ]:
#argmin 
#Returns the indices of the maximum value of all elements in the input tensor.
import torch
t=torch.randn(3,4)
print(t)
targmax=torch.max(t) # get the maximum value
print(targmax)

tensor([[-1.0373, -2.0982,  1.2370,  0.4352],
        [-0.4686,  1.2956,  0.9767, -0.5589],
        [-1.1462, -0.9271, -1.0541,  1.0327]])
tensor(1.2956)


In [ ]:
import torch
t=torch.randn(3,4)
print(t)
targmax,indexmax=torch.max(t,dim=0) # get the maximum value and index along columns
print(targmax)
print(indexmax)

tensor([[ 0.5087,  0.6886, -1.7691, -1.3141],
        [ 0.0771,  0.7158,  0.6958, -0.7172],
        [ 0.5942,  0.7958,  1.0333,  0.5869]])
tensor([0.5942, 0.7958, 1.0333, 0.5869])
tensor([2, 2, 2, 2])


In [ ]:
t=torch.randn(3,4)
print(t)
targmax,indexmax=torch.max(t,dim=1) # get the maximum value and index along rows
print(targmax)
print(indexmax)

tensor([[ 0.1326, -1.2795,  1.0979,  0.6574],
        [-1.6141, -0.8489,  0.0714, -0.5087],
        [-0.2730, -0.0967,  1.4936,  3.2443]])
tensor([1.0979, 0.0714, 3.2443])
tensor([2, 2, 3])


In [ ]:
t=torch.randn(3,4)
print(t)
targmax=torch.amax(t,dim=1) # get the maximum value along rows
print(targmax)

tensor([[-0.9363,  0.8730,  1.2600, -0.2754],
        [-1.7859,  0.7674,  0.6842,  0.4741],
        [ 0.5843, -0.9659,  0.1574, -0.6792]])
tensor([1.2600, 0.7674, 0.5843])


In [ ]:
t=torch.randn(3,4)
print(t)
targmax=torch.amax(t,dim=0) # get the maximum value along columns
print(targmax)

tensor([[-1.7248,  2.2064, -0.0134, -1.1139],
        [ 0.8638,  1.3190, -0.4403, -0.4196],
        [-0.0990,  0.0231,  0.1307, -0.4616]])
tensor([ 0.8638,  2.2064,  0.1307, -0.4196])


In [ ]:
t=torch.randn(3,4)
print(t)
targmax=torch.amin(t,dim=1) # get the minimum value along rows
print(targmax)

tensor([[-0.9172,  0.6403, -0.4964,  1.6657],
        [ 1.0856,  0.1106,  0.5485, -0.7406],
        [-1.7060,  0.6125,  1.8470,  2.2846]])
tensor([-0.9172, -0.7406, -1.7060])


In [ ]:
t=torch.randn(3,4)
print(t)
targmax=torch.amin(t,dim=0) # get the minimum value along columns
print(targmax)

tensor([[ 1.3067, -2.0033, -1.8034, -0.4414],
        [ 0.3724,  1.3939,  0.8970, -1.4501],
        [-1.1425,  1.4001,  0.2971,  0.3405]])
tensor([-1.1425, -2.0033, -1.8034, -1.4501])


In [ ]:
t=torch.randn(3,4)
print(t)
tmean=torch.randn(3,4).mean()
tsum=torch.randn(3,4).sum()
tstd=torch.randn(3,4).std()
tmode=torch.randn(3,4).mode()
tvar=torch.randn(3,4).var()
tcount=torch.count_nonzero(t) # compute non zeros values
tcountr=torch.count_nonzero(t,dim=1) # non zeros value along rows
tcountc=torch.count_nonzero(t,dim=0) # non zeros values along cloumns
tunque=torch.unique(t) # check unique values in torch tensor
print(tmean)
print(tsum)
print(tstd)
print(tmode)
print(tvar)
print(tcount)
print(tcountr)
print(tcountc)
print(tunque)

tensor([[ 1.2431,  0.8653, -0.3054,  0.9072],
        [-1.8067, -1.2869,  1.1266,  0.0823],
        [-1.6919,  1.2077,  0.5265, -1.2120]])
tensor(-0.1930)
tensor(-2.9284)
tensor(0.7634)
torch.return_types.mode(
values=tensor([-0.3517, -1.0964, -1.4022]),
indices=tensor([1, 3, 1]))
tensor(1.1269)
tensor(12)
tensor([4, 4, 4])
tensor([3, 3, 3, 3])
tensor([-1.8067, -1.6919, -1.2869, -1.2120, -0.3054,  0.0823,  0.5265,  0.8653,
         0.9072,  1.1266,  1.2077,  1.2431])


**Math operations**

**Pointwise Ops**

**abs**

Computes the absolute value of each element in input.

**absolute**

Alias for torch.abs()

**add**

Adds the scalar other to each element of the input input and returns a new resulting tensor.

**div**

Divides each element of the input input by the corresponding element of other.
divide

Alias for torch.div().

**mul**

Multiplies each element of the input input with the scalar other and returns a new resulting tensor.

multiply
**bold text**
Alias for torch.mul().

**sub**

Subtracts other, scaled by alpha, from input.

**subtract**

Alias for torch.sub().



**clamp**

Clamp all elements in input into the range [ min, max ] and return a resulting tensor:

**clip**

Alias for torch.clamp().

**exp**

Returns a new tensor with the exponential of the elements of the input tensor input.

**ceil**

Returns a new tensor with the ceil of the elements of input, the smallest integer greater than or equal to each element.

**floor**

Returns a new tensor with the floor of the elements of input, the largest integer less than or equal to each element.

**pow**

Takes the power of each element in input with exponent and returns a tensor with the result.

**sqrt**

Returns a new tensor with the square-root of the elements of input.

**round**

Returns a new tensor with each of the elements of input rounded to the closest integer.



In [ ]:
t=torch.randn(3,4)
abst=torch.abs(t)
print(abst)

tensor([[0.8168, 1.4310, 1.8034, 1.3966],
        [0.4173, 1.3947, 2.1197, 1.0831],
        [0.3468, 0.1536, 1.3229, 0.0438]])


In [ ]:
t=torch.randn(3,4)
texp=torch.exp(t)
tciel=torch.ceil(t)
tfloor=torch.floor(t)
print(texp)
print(tciel)
print(tfloor)

tensor([[4.4054, 1.3841, 1.2024, 2.8324],
        [0.6610, 0.6376, 0.4153, 0.6705],
        [0.8619, 3.2818, 0.8822, 2.3641]])
tensor([[2., 1., 1., 2.],
        [-0., -0., -0., -0.],
        [-0., 2., -0., 1.]])
tensor([[ 1.,  0.,  0.,  1.],
        [-1., -1., -1., -1.],
        [-1.,  1., -1.,  0.]])


In [ ]:
t1=torch.tensor([[1,3],[2,3],[5,6]])
t2=torch.tensor([[3,1],[4,6],[2,3]])
addt=torch.add(t1,t2)
subt=torch.sub(t1,t2)
divt=torch.div(t1,t2)
mult=torch.mul(t1,t2)
print(addt)
print(subt)
print(divt)
print(mult)

tensor([[4, 4],
        [6, 9],
        [7, 9]])
tensor([[-2,  2],
        [-2, -3],
        [ 3,  3]])
tensor([[0.3333, 3.0000],
        [0.5000, 0.5000],
        [2.5000, 2.0000]])
tensor([[ 3,  3],
        [ 8, 18],
        [10, 18]])


**Random sampling**

seed
**bold text**
Sets the seed for generating random numbers to a non-deterministic random number.

**manual_seed**

Sets the seed for generating random numbers.

**initial_seed**

Returns the initial seed for generating random numbers as a Python long.

**get_rng_state**

Returns the random number generator state as a torch.ByteTensor.

**set_rng_state**

Sets the random number generator state.


**torch.default_generator Returns the default CPU torch.Generator**

**bernoulli**

Draws binary random numbers (0 or 1) from a Bernoulli distribution.

**multinomial**

Returns a tensor where each row contains num_samples indices sampled from the multinomial probability distribution located in the corresponding row of tensor input.

**normal**

Returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

**poisson**

Returns a tensor of the same size as input with each element sampled from a Poisson distribution with rate parameter given by the corresponding element in input i.e.,

**rand**

Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)[0,1)

**rand_like**

Returns a tensor with the same size as input that is filled with random numbers from a uniform distribution on the interval [0, 1)[0,1) .

**randint**

Returns a tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).

**randint_like**

Returns a tensor with the same shape as Tensor input filled with random integers generated uniformly between low (inclusive) and high (exclusive).

**randn**

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).

**randn_like**

Returns a tensor with the same size as input that is filled with random numbers from a normal distribution with mean 0 and variance 1.

**randperm**

Returns a random permutation of integers from 0 to n - 1.



In [ ]:
a=torch.ones(5,5)
bt=torch.bernoulli(a)
print(bt)
a1 = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random 
bt1=torch.bernoulli(a1)
print(bt1)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


In [ ]:
a1 = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random 
bm1=torch.multinomial(a1,2)
print(bm1)

tensor([[1, 0],
        [0, 1],
        [2, 1]])


In [ ]:
import torch
inpt=torch.rand(21,21)
print(inpt.shape) #check shape
print(inpt.size()) # check size
print(inpt.ndimension()) # how many dimensions in torch tensor

torch.Size([21, 21])
torch.Size([21, 21])
2


In [ ]:
import torch
inpt=torch.randn(21,21)
#print(inpt)
print(inpt.shape) #check shape
print(inpt.size()) # check size
print(inpt.ndimension()) # how many dimensions in torch tensor

torch.Size([21, 21])
torch.Size([21, 21])
2


In [ ]:
import torch
inpt=torch.empty(2,2) # can use empty for random function
print(inpt)
print(inpt.shape) #check shape
print(inpt.size()) # check size
print(inpt.ndimension()) # how many dimensions in torch tensor

tensor([[5.3598e-36, 0.0000e+00],
        [1.5975e-43, 1.3873e-43]])
torch.Size([2, 2])
torch.Size([2, 2])
2


**TENSOR VIEWS**

PyTorch allows a tensor to be a View of an existing tensor. 

View tensor shares the same underlying data with its base tensor. Supporting View avoids explicit data copy, 

thus allows us to do fast and **memory efficient reshaping, slicing and element-wise operations.**

**For reference, here’s a full list of view ops in PyTorch:**
https://pytorch.org/docs/stable/tensor_view.html

Basic slicing and indexing op, e.g. tensor[0, 2:, 1:7:2] returns a view of base tensor, see note below.

as_strided(), 

**detach()**

diagonal()

expand()

expand_as()

**movedim()**

narrow()

**permute()**

select()

**squeeze()**

**transpose()** 

t()

T

real

imag

view_as_real()

view_as_imag()

unflatten()

unfold()

**unsqueeze()**

**view()**

view_as()

unbind()

split()

split_with_sizes()

chunk()

indices() (sparse tensor only)

values() (sparse tensor only) 


In [ ]:
x = torch.tensor([[1], [2], [3]])
t1=x.expand(3,3)
print(t1)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


In [8]:
import torch
x=torch.randn(4,4)
y=x.view(16)
print(y)
print(y.shape)
z=x.view(-1,8)
print(z.shape)

tensor([-1.5730,  0.1533, -1.4589,  1.8699, -0.5129,  0.2044, -0.6718, -0.0992,
         0.6227,  0.7371,  1.4240,  0.5871,  0.6675, -1.0378, -0.2390,  3.0997])
torch.Size([16])
torch.Size([2, 8])


In [11]:
a = torch.randn(1, 2, 3, 4)
print(a.shape)
b=a.transpose(1,2) # Swaps 2nd and 3rd dimension
print(b.shape)
c=b.view(1,3,2,4) # does not chnage tensor layeout in memory
print(c.shape)
print(torch.equal(b, c))

torch.Size([1, 2, 3, 4])
torch.Size([1, 3, 2, 4])
torch.Size([1, 3, 2, 4])
True


In [18]:
base_t=torch.tensor([[0,1],[2,3]])
print(base_t.is_contiguous())
t=base_t.transpose(0,1) #
print(t.is_contiguous()) #View tensors might be non-contiguous.
c = t.contiguous()
print(c.is_contiguous())

True
False
True


In [27]:
base_t=torch.tensor([[0,1],[2,3],[5,4]])
print(base_t.is_contiguous())
t=base_t.view(-1,2) # two coulmns, all rows
print(t)
print(t.is_contiguous()) #View tensors is contiguous.
#c = t.contiguous()
#print(c.is_contiguous())
t1=base_t.view(2,-1) # two rows, all columns
print(t1.is_contiguous()) #View tensors is contiguous.
print(t1)

True
tensor([[0, 1],
        [2, 3],
        [5, 4]])
True
True
tensor([[0, 1, 2],
        [3, 5, 4]])


In [34]:
x=torch.randn(5,4,3)
print(x.is_contiguous())
print(x.size())
y=x.permute(2,0,1) # swap the diemsnion and memory is non-contiguous
print(y.is_contiguous())
print(y.size())
y=x.permute(2,0,1) # swap the diemsnion 
y2=y.contiguous()
print(y2.is_contiguous())

True
torch.Size([5, 4, 3])
False
torch.Size([3, 5, 4])
True
