In [1]:
import torch
import torch.nn as nn
a=torch.randn(4,3,28,28)

In [2]:
a[0].shape

torch.Size([3, 28, 28])

In [3]:
a[0,0].shape

torch.Size([28, 28])

In [4]:
a[0,0,2,4].shape

torch.Size([])

In [5]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [6]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [7]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

In [8]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [9]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [10]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

In [11]:
a[0,...].shape

torch.Size([3, 28, 28])

In [12]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [13]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [14]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

In [15]:
a[0,...,::2].shape

torch.Size([3, 28, 14])

In [16]:
a[...,::2].shape

torch.Size([4, 3, 28, 14])

In [19]:
x=torch.rand(3,4)
x

tensor([[0.3427, 0.7481, 0.9730, 0.4735],
        [0.1295, 0.1298, 0.6319, 0.5024],
        [0.0191, 0.3588, 0.1325, 0.0357]])

In [20]:
mask=x.ge(0.5)
mask

tensor([[False,  True,  True, False],
        [False, False,  True,  True],
        [False, False, False, False]])

In [21]:
torch.masked_select(x,mask)

tensor([0.7481, 0.9730, 0.6319, 0.5024])

In [23]:
b=torch.rand(4,1,28,28)
b.shape

torch.Size([4, 1, 28, 28])

In [25]:
b.view(4,28*28).shape

torch.Size([4, 784])

In [26]:
b.view(4*28,28).shape

torch.Size([112, 28])

In [27]:
b.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [29]:
c=b.view(4,784)
c.shape

torch.Size([4, 784])

In [31]:
b.shape

torch.Size([4, 1, 28, 28])

In [32]:
b.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [33]:
b.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [34]:
b.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [35]:
b.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [36]:
b.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [37]:
b.unsqueeze(5).shape

IndexError: ignored

In [41]:
a=torch.tensor([1.2,2.3])
a.shape

torch.Size([2])

In [42]:
a.unsqueeze(-1).shape

torch.Size([2, 1])

In [43]:
a.unsqueeze(0).shape

torch.Size([1, 2])

In [53]:
b=torch.rand(32)

In [54]:
b.unsqueeze(1).shape

torch.Size([32, 1])

In [56]:
c=b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
c.shape

torch.Size([1, 32, 1, 1])

In [57]:
f=torch.rand(4,32,14,14)

In [60]:
(c+f).shape

torch.Size([4, 32, 14, 14])

In [62]:
c.squeeze().shape

torch.Size([32])

In [63]:
c.squeeze(0).shape

torch.Size([32, 1, 1])

In [64]:
c.squeeze(-1).shape

torch.Size([1, 32, 1])

In [65]:
c.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [66]:
c.squeeze(-4).shape

torch.Size([32, 1, 1])

In [67]:
c.shape

torch.Size([1, 32, 1, 1])

In [68]:
c.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [70]:
c.expand(-1,32,-1,-1).shape

torch.Size([1, 32, 1, 1])

In [71]:
c.expand(-1,32,-1,-4).shape

torch.Size([1, 32, 1, -4])

In [72]:
c.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [73]:
c.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [74]:
c.repeat(4,32,32,32).shape

torch.Size([4, 1024, 32, 32])

In [75]:
c.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

In [77]:
a=torch.rand(4,3,28,28)
a1=a.transpose(1,3).view(4,3*28*28).view(4,3,28,28)

RuntimeError: ignored

In [80]:
a1=a.transpose(1,3).contiguous().view(4,3*28*28).view(4,3,28,28)
a1.shape

torch.Size([4, 3, 28, 28])

In [82]:
a2=a.transpose(1,3).contiguous().view(4,3*28*28).view(4,28,28,3).transpose(1,3)
a2.shape

torch.Size([4, 3, 28, 28])

In [83]:
a=torch.randn(4,3,28,28)
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [84]:
b=torch.randn(4,3,28,32)
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [86]:
b.shape

torch.Size([4, 3, 28, 32])

In [85]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [87]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])

In [91]:
a=torch.rand(5,8,3)
b=torch.rand(4,8,3)
c=torch.cat([a,b],dim=0)
c.shape

torch.Size([9, 8, 3])

In [92]:
a1=torch.rand(4,3,32,32)
a2=torch.rand(5,3,32,32)
c=torch.cat([a1,a2],dim=0)
c.shape

torch.Size([9, 3, 32, 32])

In [93]:
a1=torch.rand(4,3,32,32)
a2=torch.rand(4,6,32,32)
c=torch.cat([a1,a2],dim=1)
c.shape

torch.Size([4, 9, 32, 32])

In [94]:
a1=torch.rand(4,3,32,16)
a2=torch.rand(4,3,32,16)
c=torch.cat([a1,a2],dim=3)
c.shape

torch.Size([4, 3, 32, 32])

In [102]:
a1=torch.rand(4,3,32,16)
a2=torch.rand(4,3,32,16)
c=torch.stack([a1,a2],dim=0)
c.shape

torch.Size([2, 4, 3, 32, 16])

In [103]:
a1=torch.rand(4,3,32,16)
a2=torch.rand(4,3,32,16)
c=torch.stack([a1,a2],dim=2)
c.shape

torch.Size([4, 3, 2, 32, 16])

In [95]:
a=torch.rand(3,32)
b=torch.rand(3,32)
d=torch.stack([a,b],dim=0)
d.shape

torch.Size([2, 3, 32])

In [96]:
a=torch.rand(3,32)
b=torch.rand(3,32)
d=torch.stack([a,b],dim=1)
d.shape

torch.Size([3, 2, 32])

In [104]:
a=torch.rand(4,8)
a.argmax()

tensor(28)

In [107]:
a

tensor([[0.1150, 0.2594, 0.8232, 0.8073, 0.6700, 0.2744, 0.4863, 0.8307],
        [0.7616, 0.2781, 0.0663, 0.7333, 0.0791, 0.5736, 0.2623, 0.5132],
        [0.7412, 0.8321, 0.5007, 0.7274, 0.4445, 0.6819, 0.2558, 0.2668],
        [0.3597, 0.7817, 0.2116, 0.2919, 0.9565, 0.7037, 0.7985, 0.6197]])

In [106]:
a.argmax(dim=1)

tensor([7, 0, 1, 4])

In [108]:
a.argmax(dim=0)

tensor([1, 2, 0, 0, 3, 3, 3, 0])

In [109]:
a.max(dim=1)

torch.return_types.max(values=tensor([0.8307, 0.7616, 0.8321, 0.9565]), indices=tensor([7, 0, 1, 4]))

In [110]:
a.max(dim=1,keepdim=True)

torch.return_types.max(values=tensor([[0.8307],
        [0.7616],
        [0.8321],
        [0.9565]]), indices=tensor([[7],
        [0],
        [1],
        [4]]))

In [111]:
a.argmax(dim=1,keepdim=True)

tensor([[7],
        [0],
        [1],
        [4]])

In [112]:
a>0

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])

In [113]:
torch.gt(a,0)

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])

In [115]:
a!=0

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])