In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive/

/content/drive/MyDrive


In [4]:
# Building seqeuntial modules of the network
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torchvision.transforms as transforms

import matplotlib.pyplot as plt
import math

from collections import OrderedDict

torch.set_printoptions(linewidth=150)


In [ ]:
linear_regression_model = nn.Linear(in_features=5, out_features=2)  # Linear <=> Fully Connected in_features=colums, out_features=rows 2x5

In [5]:
#Creation and Usage
#Instantiate a Linear module from the torch.nn library
FC_layer=nn.Linear(in_features=5,out_features=2) # linear or fully connected layers
print(FC_layer)

Linear(in_features=5, out_features=2, bias=True)


In [8]:
# Parameters of a module are randomly initialised
FC_layer.weight

Parameter containing:
tensor([[-0.2921, -0.1447, -0.0386,  0.2053,  0.1201],
        [-0.0425,  0.2147,  0.3936, -0.1369,  0.1212]], requires_grad=True)

In [9]:
# shape of weight matrix
FC_layer.weight.shape

torch.Size([2, 5])

In [10]:
# type
type(FC_layer.weight)
#A Parameter is a Tensor which is automatically added to the list of parameters when used within a model.

torch.nn.parameter.Parameter

In [15]:
dir(FC_layer)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_version',
 'add_module',
 'apply',
 'bfloat16',
 'bias',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double

In [14]:
# check all module parameters
for name, tensor in FC_layer.named_parameters():
  print("{:6s} :: {}".format(name,tensor))

weight :: Parameter containing:
tensor([[-0.2921, -0.1447, -0.0386,  0.2053,  0.1201],
        [-0.0425,  0.2147,  0.3936, -0.1369,  0.1212]], requires_grad=True)
bias   :: Parameter containing:
tensor([0.0708, 0.0822], requires_grad=True)


In [16]:
list(FC_layer.parameters())

[Parameter containing:
 tensor([[-0.2921, -0.1447, -0.0386,  0.2053,  0.1201],
         [-0.0425,  0.2147,  0.3936, -0.1369,  0.1212]], requires_grad=True),
 Parameter containing:
 tensor([0.0708, 0.0822], requires_grad=True)]

In [27]:
print("Weight matrix: W----------", list(FC_layer.parameters())[0])

Weight matrix: W---------- Parameter containing:
tensor([[-0.2921, -0.1447, -0.0386,  0.2053,  0.1201],
        [-0.0425,  0.2147,  0.3936, -0.1369,  0.1212]], requires_grad=True)


In [26]:
print("bias Vector: W------", list(FC_layer.parameters())[1])

bias Vector: W------ Parameter containing:
tensor([0.0708, 0.0822], requires_grad=True)


In [ ]:
# Pytorch Modules operate on batches. It allows to process multiple datapoints in parallel
# All modules in torch.nn are written to produce outputs for a batch of multiple inputs at the same time.

batch_size = 3
feature_size = 5
x = torch.randn(batch_size, feature_size) # batch of 3 samples with 5 features each

print(x, "\n\n", x.shape)

In [28]:
# testing our model using input tensor
#Calling a module on an input Tensor
# Pytorch Modules operate on batches. It allows to process multiple datapoints in parallel
# All modules in torch.nn are written to produce outputs for a batch of multiple inputs at the same time
batch=3
feature_size=5
x=torch.randn(batch,feature_size) # batch is 3 and number of features in each batch are 5
print(x,'\n\n',x.shape)

tensor([[-0.2625,  1.0284, -1.7102, -0.1373,  1.0268],
        [-0.3938,  0.2395,  0.7747, -0.1808,  1.2172],
        [-0.5812,  1.2153,  0.8329, -1.1733,  1.1772]]) 

 torch.Size([3, 5])


In [ ]:
# predict the model by passing the input
predicted_y = FC_layer(x)  # Note, you do not call explicitely forward
print(predicted_y, "\n\n", predicted_y.shape)

In [29]:
# predict the model by passing the input
# please note that model does nit call explicitely the forward
predict_y=FC_layer(x)
print(predict_y,'\n\n',predict_y.shape)

tensor([[ 0.1598, -0.2157],
        [ 0.2303,  0.6275],
        [-0.0669,  0.9990]], grad_fn=<AddmmBackward>) 

 torch.Size([3, 2])


**Composing modules with torch.nn.Sequential**

In [30]:
# create model with more than one layer you need to call Sequential module in order to construct the module
model_Se=torch.nn.Sequential(torch.nn.Linear(10,5),
                             torch.nn.ReLU(),
                             torch.nn.Linear(5,2))
print(model_Se)

Sequential(
  (0): Linear(in_features=10, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=2, bias=True)
)


In [40]:
# check all module parameters
for name, tensor in model_Se.named_parameters():
  print("{:6s} :: {}".format(name,tensor))

0.weight :: Parameter containing:
tensor([[ 0.3032,  0.1379, -0.1578,  0.2427, -0.0187, -0.1108,  0.1881, -0.0033, -0.1712,  0.1225],
        [-0.1371, -0.2180, -0.0114, -0.0336,  0.2753, -0.0592,  0.0125,  0.0607,  0.1637,  0.1845],
        [-0.1453, -0.2928, -0.2854, -0.0990, -0.1174,  0.1572, -0.0596, -0.1366, -0.1658, -0.1852],
        [ 0.2594,  0.0170,  0.2149, -0.1464,  0.1914, -0.0888, -0.2942, -0.2958,  0.3089, -0.2167],
        [-0.2407,  0.1749, -0.0986,  0.0878, -0.2719,  0.1038,  0.1281, -0.1711,  0.2746,  0.1509]], requires_grad=True)
0.bias :: Parameter containing:
tensor([-0.1143,  0.0344, -0.1815,  0.2258, -0.3012], requires_grad=True)
2.weight :: Parameter containing:
tensor([[-0.3607,  0.4178,  0.3310,  0.1413,  0.4271],
        [-0.3792,  0.1631,  0.0703, -0.2714,  0.2967]], requires_grad=True)
2.bias :: Parameter containing:
tensor([-0.2935,  0.1030], requires_grad=True)


In [35]:
print("layer1 weight: W1", list(model_Se.parameters())[0],'\n\n',list(model_Se.parameters())[0].shape)

layer1 weight: W1 Parameter containing:
tensor([[ 0.3032,  0.1379, -0.1578,  0.2427, -0.0187, -0.1108,  0.1881, -0.0033, -0.1712,  0.1225],
        [-0.1371, -0.2180, -0.0114, -0.0336,  0.2753, -0.0592,  0.0125,  0.0607,  0.1637,  0.1845],
        [-0.1453, -0.2928, -0.2854, -0.0990, -0.1174,  0.1572, -0.0596, -0.1366, -0.1658, -0.1852],
        [ 0.2594,  0.0170,  0.2149, -0.1464,  0.1914, -0.0888, -0.2942, -0.2958,  0.3089, -0.2167],
        [-0.2407,  0.1749, -0.0986,  0.0878, -0.2719,  0.1038,  0.1281, -0.1711,  0.2746,  0.1509]], requires_grad=True) 

 torch.Size([5, 10])


In [36]:
print("layer1 Bais: b1", list(model_Se.parameters())[1],'\n\n',list(model_Se.parameters())[1].shape)

layer1 Bais: b1 Parameter containing:
tensor([-0.1143,  0.0344, -0.1815,  0.2258, -0.3012], requires_grad=True) 

 torch.Size([5])


In [38]:
print("layer2 weight: W2", list(model_Se.parameters())[2],'\n\n',list(model_Se.parameters())[2].shape)

layer2 weight: W2 Parameter containing:
tensor([[-0.3607,  0.4178,  0.3310,  0.1413,  0.4271],
        [-0.3792,  0.1631,  0.0703, -0.2714,  0.2967]], requires_grad=True) 

 torch.Size([2, 5])


In [39]:
print("layer2 bias: b2", list(model_Se.parameters())[3],'\n\n',list(model_Se.parameters())[3].shape)

layer2 bias: b2 Parameter containing:
tensor([-0.2935,  0.1030], requires_grad=True) 

 torch.Size([2])


In [41]:
x = torch.rand(5, 10)   # the first dimension is reserved for the 'batch_size'
print(x,'\n\n',x.shape)

tensor([[0.3715, 0.6171, 0.2972, 0.5623, 0.1428, 0.5729, 0.5608, 0.2745, 0.5644, 0.2411],
        [0.1538, 0.0830, 0.7820, 0.7782, 0.5272, 0.7269, 0.9030, 0.3738, 0.8695, 0.6880],
        [0.4501, 0.1457, 0.5583, 0.0305, 0.3618, 0.2661, 0.3220, 0.2477, 0.4339, 0.3975],
        [0.6372, 0.2485, 0.5399, 0.0325, 0.0568, 0.9038, 0.2371, 0.3033, 0.0415, 0.3999],
        [0.6909, 0.8005, 0.3387, 0.8803, 0.1240, 0.7859, 0.7289, 0.2110, 0.2104, 0.1672]]) 

 torch.Size([5, 10])


In [43]:
# test model prediction
prediction_model=model_Se(x)
print("model prediction:",prediction_model,'\n\n', prediction_model.shape)

model prediction: tensor([[-0.3220,  0.0031],
        [-0.1347,  0.1266],
        [-0.1634,  0.0277],
        [-0.2719,  0.0401],
        [-0.4271, -0.0662]], grad_fn=<AddmmBackward>) 

 torch.Size([5, 2])


**There are three ways to build models in sequentially:**

**First method:**


In [48]:
torch.manual_seed(50)
# First method is starightforward and simple 
Sequentialfirst=nn.Sequential(nn.Conv2d(in_channels=3,out_channels=5,kernel_size=3), #3x100x100=98x98
                              nn.ReLU(),
                              nn.MaxPool2d(kernel_size=2,stride=2), #49x49
                              nn.Conv2d(in_channels=5,out_channels=10,kernel_size=4),#46x46
                              nn.ReLU(),
                              nn.MaxPool2d(kernel_size=2,stride=2), #23x23
                              nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3), #21x21
                              nn.ReLU(),
                              nn.MaxPool2d(kernel_size=3,stride=3), #7x7
                              nn.Flatten(start_dim=1),
                              nn.ReLU(),
                              nn.Linear(in_features=10*7*7,out_features=60),
                              nn.ReLU(),
                              nn.Linear(in_features=60,out_features=10))

In [49]:
print(Sequentialfirst)

Sequential(
  (0): Conv2d(3, 5, kernel_size=(3, 3), stride=(1, 1))
  (1): ReLU()
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (3): Conv2d(5, 10, kernel_size=(4, 4), stride=(1, 1))
  (4): ReLU()
  (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (6): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1))
  (7): ReLU()
  (8): MaxPool2d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (9): Flatten(start_dim=1, end_dim=-1)
  (10): ReLU()
  (11): Linear(in_features=490, out_features=60, bias=True)
  (12): ReLU()
  (13): Linear(in_features=60, out_features=10, bias=True)
)


In [52]:
# input tensor module for testing our model
x=torch.randn((5,3,100,100))
out=Sequentialfirst(x)
print("print output prediction",out,'\n\n',out.shape)

print output prediction tensor([[ 0.1395, -0.0426, -0.0218, -0.1908, -0.1048, -0.0873,  0.1465,  0.0050, -0.0887,  0.1354],
        [ 0.1261, -0.0473, -0.0340, -0.1824, -0.0943, -0.0894,  0.1433,  0.0170, -0.0986,  0.1418],
        [ 0.1351, -0.0404, -0.0253, -0.1787, -0.0917, -0.0905,  0.1416,  0.0204, -0.0900,  0.1416],
        [ 0.1240, -0.0481, -0.0369, -0.1893, -0.0785, -0.0976,  0.1374,  0.0088, -0.0861,  0.1483],
        [ 0.1280, -0.0398, -0.0292, -0.1829, -0.0824, -0.0886,  0.1304,  0.0166, -0.0961,  0.1432]], grad_fn=<AddmmBackward>) 

 torch.Size([5, 10])


In [60]:
# second method to construct sequential model
network2=nn.Sequential()
network2.add_module('c1',nn.Conv2d(in_channels=3,out_channels=5,kernel_size=3))
network2.add_module('act1',nn.ReLU())
network2.add_module('maxpool1',nn.MaxPool2d(kernel_size=2,stride=2))
network2.add_module('c2',nn.Conv2d(in_channels=5,out_channels=10,kernel_size=4))
network2.add_module('act2',nn.ReLU())
network2.add_module('maxpool2',nn.MaxPool2d(kernel_size=2,stride=2))
network2.add_module('c3',nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3))
network2.add_module('act3',nn.ReLU())
network2.add_module('maxpool3',nn.MaxPool2d(kernel_size=3,stride=3))
network2.add_module('flatten',nn.Flatten(start_dim=1))
network2.add_module('act4',nn.ReLU())
network2.add_module('Linear1',nn.Linear(in_features=10*7*7,out_features=60))
network2.add_module('act5',nn.ReLU())
network2.add_module('Linear2',nn.Linear(in_features=60,out_features=10))
print(network2)


Sequential(
  (c1): Conv2d(3, 5, kernel_size=(3, 3), stride=(1, 1))
  (act1): ReLU()
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (c2): Conv2d(5, 10, kernel_size=(4, 4), stride=(1, 1))
  (act2): ReLU()
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (c3): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1))
  (act3): ReLU()
  (maxpool3): MaxPool2d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (act4): ReLU()
  (Linear1): Linear(in_features=490, out_features=60, bias=True)
  (act5): ReLU()
  (Linear2): Linear(in_features=60, out_features=10, bias=True)
)


In [61]:
# input tensor module for testing our model
x=torch.randn((5,3,100,100))
out=network2(x)
print("print output prediction",out,'\n\n',out.shape)

print output prediction tensor([[ 0.0005, -0.0778, -0.2369,  0.1233, -0.0161, -0.0700, -0.1477, -0.1387, -0.1692, -0.0811],
        [ 0.0097, -0.0944, -0.2299,  0.1215, -0.0102, -0.0715, -0.1421, -0.1507, -0.1728, -0.0704],
        [ 0.0121, -0.0732, -0.2339,  0.1195, -0.0244, -0.0412, -0.1456, -0.1666, -0.1733, -0.0549],
        [ 0.0142, -0.0522, -0.2380,  0.1211, -0.0041, -0.0596, -0.1382, -0.1526, -0.1735, -0.0733],
        [-0.0024, -0.0722, -0.2369,  0.1221,  0.0160, -0.0620, -0.1516, -0.1496, -0.1648, -0.0766]], grad_fn=<AddmmBackward>) 

 torch.Size([5, 10])


In [65]:
# Method 3
networks3_layers = OrderedDict([
    ('c1',nn.Conv2d(in_channels=3,out_channels=5,kernel_size=3))
   ,('act1',nn.ReLU())
   ,('maxpool1',nn.MaxPool2d(kernel_size=2,stride=2))
   ,('c2',nn.Conv2d(in_channels=5,out_channels=10,kernel_size=4)),
   ('act2',nn.ReLU()),
   ('maxpool2',nn.MaxPool2d(kernel_size=2,stride=2)),
   ('c3',nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3)),
   ('act3',nn.ReLU()),
   ('maxpool3',nn.MaxPool2d(kernel_size=3,stride=3)),
   ('flatten',nn.Flatten(start_dim=1)),
   ('act4',nn.ReLU()),
   ('Linear1',nn.Linear(in_features=10*7*7,out_features=60)),
   ('act5',nn.ReLU()),
   ('Linear2',nn.Linear(in_features=60,out_features=10))
])

network3 = nn.Sequential(networks3_layers)
print(network3)


Sequential(
  (c1): Conv2d(3, 5, kernel_size=(3, 3), stride=(1, 1))
  (act1): ReLU()
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (c2): Conv2d(5, 10, kernel_size=(4, 4), stride=(1, 1))
  (act2): ReLU()
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (c3): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1))
  (act3): ReLU()
  (maxpool3): MaxPool2d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (act4): ReLU()
  (Linear1): Linear(in_features=490, out_features=60, bias=True)
  (act5): ReLU()
  (Linear2): Linear(in_features=60, out_features=10, bias=True)
)


In [66]:
# input tensor module for testing our model
x=torch.randn((5,3,100,100))
out=network3(x)
print("print output prediction",out,'\n\n',out.shape)

print output prediction tensor([[-0.0876,  0.0998, -0.0502, -0.0477,  0.0093, -0.0766, -0.0519, -0.0143, -0.0529,  0.0811],
        [-0.0721,  0.0983, -0.0410, -0.0573,  0.0035, -0.0721, -0.0417, -0.0100, -0.0501,  0.0736],
        [-0.0839,  0.0947, -0.0201, -0.0443,  0.0028, -0.0859, -0.0419,  0.0096, -0.0358,  0.0897],
        [-0.0716,  0.0858, -0.0266, -0.0530,  0.0012, -0.0785, -0.0422, -0.0178, -0.0173,  0.0908],
        [-0.0848,  0.1014, -0.0332, -0.0463,  0.0045, -0.0721, -0.0303, -0.0037, -0.0262,  0.0736]], grad_fn=<AddmmBackward>) 

 torch.Size([5, 10])


In [73]:
import torch.nn.functional as F
class definemodel(nn.Module):
  def __init__(self):
    super().__init__()

    self.C1=nn.Conv2d(3,5,3)
    self.C2=nn.Conv2d(5,10,4)
    self.C3=nn.Conv2d(10,10,3)
    self.linear1=nn.Linear(in_features=10*7*7,out_features=60)
    self.linear2=nn.Linear(in_features=60,out_features=10)
  
  def forward(self,x):
    x=F.relu(self.C1(x))
    x=F.max_pool2d(x,kernel_size=2,stride=2)
    x=F.relu(self.C2(x))
    x=F.max_pool2d(x,kernel_size=2,stride=2)
    x=F.relu(self.C3(x))
    x=F.max_pool2d(x,kernel_size=3,stride=3)
    x=x.flatten(start_dim=1)
    x=F.relu(self.linear1(x))
    x=F.relu(self.linear2(x))
    
    return x

model3=definemodel()
print(model3)

definemodel(
  (C1): Conv2d(3, 5, kernel_size=(3, 3), stride=(1, 1))
  (C2): Conv2d(5, 10, kernel_size=(4, 4), stride=(1, 1))
  (C3): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1))
  (linear1): Linear(in_features=490, out_features=60, bias=True)
  (linear2): Linear(in_features=60, out_features=10, bias=True)
)


In [74]:
# input tensor module for testing our model
x=torch.randn((5,3,100,100))
out=model3(x)
print("print output prediction",out,'\n\n',out.shape)

print output prediction tensor([[0.0000, 0.1041, 0.0000, 0.1432, 0.1448, 0.0000, 0.1102, 0.0000, 0.0000, 0.0764],
        [0.0000, 0.0906, 0.0000, 0.1302, 0.1365, 0.0000, 0.1134, 0.0000, 0.0000, 0.0678],
        [0.0000, 0.1052, 0.0000, 0.1418, 0.1447, 0.0000, 0.1121, 0.0000, 0.0054, 0.0873],
        [0.0000, 0.0973, 0.0000, 0.1525, 0.1477, 0.0000, 0.1092, 0.0000, 0.0061, 0.0738],
        [0.0000, 0.0910, 0.0000, 0.1443, 0.1393, 0.0000, 0.1084, 0.0000, 0.0088, 0.0791]], grad_fn=<ReluBackward0>) 

 torch.Size([5, 10])


**Building Custom module**

In [84]:
# simple fully connected model
import torch.nn.functional as F

class MyNeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size,hidden_size1, num_classes):
        super(MyNeuralNetwork, self).__init__()
        
        self.linear_1 = nn.Linear(input_size, hidden_size)
        self.linear_2 = nn.Linear(hidden_size, hidden_size1)
        self.linear_3 = nn.Linear(hidden_size1, num_classes)
    
    def forward(self, x):
        out = F.relu(self.linear_1(x))
        out=F.relu(self.linear_2(out))
        out = self.linear_3(out)
        return out

In [85]:
model = MyNeuralNetwork(input_size=10, hidden_size=5,hidden_size1=15,  num_classes=2)
print(model)

MyNeuralNetwork(
  (linear_1): Linear(in_features=10, out_features=5, bias=True)
  (linear_2): Linear(in_features=5, out_features=15, bias=True)
  (linear_3): Linear(in_features=15, out_features=2, bias=True)
)


In [86]:
x=torch.randn(5,10)
output=model(x)
print(output.shape)

torch.Size([5, 2])
